### ISSUE TITLE
How do I use the latest upstream version?

### ISSUE THREAD

**Issue by iainelder** [Mateusz-Grzelinski/actionlint-py#1]
I would like to use this wrapper to simplify the installation of dependencies in my GitHub workflows. In one of my projects, actionlint is the only dependency that isn't a Python package.

The latest version of your wrapper is 1.6.24.

The latest version of the upstream project is 1.6.25.

It seems a trivial difference now, but that gap will grow. Without a clear way for me to get the latest upstream version I'm hesitant to depend on this wrapper.

**Comment by Mateusz-Grzelinski** [comment]
Well, if you are doing something production, then it is not a great idea to depend on this repo.
This is my first time releasing the package, and the forked code is not obvious, although I managed to develop nice automation for it. 
I just updated it to newest version.
I just updated readme and documented a bit more. 
The best way would be to probably automate it fully...
What would you like to see in this repo? I simply made it to make my life a bit easier.

**Comment by Mateusz-Grzelinski** [comment]
I would love to move away from setup.py but learning how to extend build system in pyproject.toml is quite involving.

**Comment by iainelder** [comment]
Thanks! I will try it now to replace the "Install actionlint" step of [my workflow](https://github.com/iainelder/aws-org-tree/blob/master/.github/workflows/publish.yaml) with your pre-commit hook.

My own pre-commit hook looks like this:

```yaml
      - id: actionlint
        name: actionlint
        entry: actionlint
        types: [yaml]
        files: .github/workflows
        language: system
```

And I install actionlint like this:

```yaml
      - name: Install actionlint
        uses: giantswarm/install-binary-action@v1.1.0
        with:
          binary: actionlint
          version: 1.6.25
          download_url: "https://github.com/rhysd/actionlint/releases/download/v${version}/actionlint_${version}_linux_amd64.tar.gz"
          tarball_binary_path: "${binary}"
          smoke_test: "${binary} --version"

      - name: Install Python dependencies
        run: poetry install --no-interaction

      - name: Run pre-commit checks
        run: poetry run pre-commit run --all-files --verbose
```

> The best way would be to probably automate it fully...

You could run your auto-update script on a schedule and run the rest of the steps if it makes changes.

>  would love to move away from setup.py but learning how to extend build system in pyproject.toml is quite involving.

Have you tried [Poetry](https://python-poetry.org/)? It generates a pyproject.toml file and can manage the dependencies parts automatically.
